/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.garage;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RegCarro extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Vehículo> listaCarros = new ArrayList<Vehículo>();
    public RegCarro() {
        initComponents();
        this.setTitle("REGISTRO DE AUTOS");
        this.setLocationRelativeTo(null);
        
        modelo.addColumn("Id");
        modelo.addColumn("Tipo de vehiculo");
        modelo.addColumn("Color");
        modelo.addColumn("Num. Placa");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Lunas Polarizadas"); 
        refrescarTabla();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLOGIN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ListaCarro = new javax.swing.JLabel();
        cbxTipVehiculo = new javax.swing.JComboBox<>();
        ColorVehi = new javax.swing.JLabel();
        TipoVehi = new javax.swing.JLabel();
        NumPlaca = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LunasPola = new javax.swing.JLabel();
        cbxColorVehi = new javax.swing.JComboBox<>();
        Modelo = new javax.swing.JLabel();
        txtNumPlaca = new javax.swing.JTextField();
        cbxLunaPolarizada = new javax.swing.JComboBox<>();
        cbxModelo = new javax.swing.JComboBox<>();
        cbxMarca = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablitaCarros = new javax.swing.JTable();
        RegCarro1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        btnLOGIN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLOGIN.setText("Acceder");
        btnLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGINActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(163, 178, 176));

        ListaCarro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ListaCarro.setForeground(new java.awt.Color(4, 160, 142));
        ListaCarro.setText("Lista de Carros");

        cbxTipVehiculo.setBackground(new java.awt.Color(204, 204, 204));
        cbxTipVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTipVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan                                                                                            ", "SUV                                                                                                ", "Pickup", "Otro", "No especificado                                                                                                     " }));
        cbxTipVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipVehiculoActionPerformed(evt);
            }
        });

        ColorVehi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ColorVehi.setText("Color");

        TipoVehi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TipoVehi.setText("Tipo de vehiculo");

        NumPlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumPlaca.setText("Num. Placa");

        Marca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Marca.setText("Marca");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        LunasPola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LunasPola.setText("Lunas Polarizadas");

        cbxColorVehi.setBackground(new java.awt.Color(204, 204, 204));
        cbxColorVehi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxColorVehi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No especificado                                                                          ", "blanco", "negro ", "gris ", "plateado ", "azul ", "rojo ", "marrón/beige ", "verde ", "amarillo/dorado" }));
        cbxColorVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxColorVehiActionPerformed(evt);
            }
        });

        Modelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Modelo.setText("Modelo");

        txtNumPlaca.setBackground(new java.awt.Color(204, 204, 204));
        txtNumPlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPlacaActionPerformed(evt);
            }
        });

        cbxLunaPolarizada.setBackground(new java.awt.Color(204, 204, 204));
        cbxLunaPolarizada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLunaPolarizada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No", "No se" }));
        cbxLunaPolarizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLunaPolarizadaActionPerformed(evt);
            }
        });

        cbxModelo.setBackground(new java.awt.Color(204, 204, 204));
        cbxModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOYOTA", "YARIS", "COROLLA", "LEXUS", "NISSAN", "SENTRA", "SUNNY", "TIDA", "VERSA", "HONDA", "FORD", "Otro" }));
        cbxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModeloActionPerformed(evt);
            }
        });

        cbxMarca.setBackground(new java.awt.Color(204, 204, 204));
        cbxMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOYOTA", "NISSAN", "HONDA", "FORD", "Otro" }));
        cbxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(4, 160, 142));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tablitaCarros.setBackground(new java.awt.Color(204, 204, 204));
        tablitaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tipo de vehiculo", "Color", "Num. Placa", "Marca", "Modelo", "Lunas Polarizadas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablitaCarros.setGridColor(new java.awt.Color(153, 153, 153));
        tablitaCarros.setRowHeight(25);
        tablitaCarros.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tablitaCarros.setShowGrid(true);
        jScrollPane1.setViewportView(tablitaCarros);

        RegCarro1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegCarro1.setForeground(new java.awt.Color(4, 160, 142));
        RegCarro1.setText("REGISTRO DE VEHÍCULOS");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(4, 160, 142));
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TipoVehi)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(cbxTipVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ColorVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxColorVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumPlaca)
                                    .addComponent(txtNumPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(88, 88, 88)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Marca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Modelo)
                                    .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LunasPola)
                                    .addComponent(cbxLunaPolarizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(647, 647, 647)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListaCarro)
                .addGap(389, 389, 389))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(341, 341, 341)
                    .addComponent(RegCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoVehi)
                    .addComponent(ColorVehi)
                    .addComponent(Marca)
                    .addComponent(LunasPola)
                    .addComponent(Modelo)
                    .addComponent(NumPlaca))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxColorVehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLunaPolarizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(ListaCarro)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(RegCarro1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipVehiculoActionPerformed

    private void cbxColorVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxColorVehiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxColorVehiActionPerformed

    private void cbxLunaPolarizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLunaPolarizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLunaPolarizadaActionPerformed

    private void cbxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModeloActionPerformed

    private void cbxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMarcaActionPerformed

    private void btnLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGINActionPerformed
    
    }//GEN-LAST:event_btnLOGINActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            Vehículo vehiculo= new Vehículo();
            
        int id;
        try {
        vehiculo.setTipo(cbxTipVehiculo.getSelectedItem().toString());
        vehiculo.setColor(cbxColorVehi.getSelectedItem().toString());
        vehiculo.setPlaca(txtNumPlaca.getText());
        vehiculo.setModelo(cbxModelo.getSelectedItem().toString());
        vehiculo.setMarca(cbxMarca.getSelectedItem().toString());
        vehiculo.setLunasPolarizadas(cbxLunaPolarizada.getSelectedItem().toString());
            listaCarros.add(vehiculo);
            refrescarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "##¡ERROR al agregar!##");
        }
        
        if (!(vehiculo.validarCampos())){
            JOptionPane.showMessageDialog(this, "##¡Inserte todos los elementos!##");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNumPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPlacaActionPerformed

    public void refrescarTabla(){
        //Borra todos los elemntos de modelo para evitar duplicado
        while(modelo.getRowCount()>0){//mientras las cnatidad de filas>0
             modelo.removeRow(0);
        }
        for (Vehículo carro : listaCarros) {
            Object vh[] = new Object [7];
            vh[1]=null;
            vh[1]=carro.getTipo();
            vh[2]=carro.getColor();
            vh[3]=carro.getPlaca();
            vh[4]=carro.getMarca();
            vh[5]=carro.getModelo();
            vh[6]=carro.getModelo();
            modelo.addRow(vh);
            
        }
        tablitaCarros.setModel(modelo);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorVehi;
    private javax.swing.JLabel ListaCarro;
    private javax.swing.JLabel LunasPola;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel NumPlaca;
    private javax.swing.JLabel RegCarro1;
    private javax.swing.JLabel TipoVehi;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLOGIN;
    private javax.swing.JComboBox<String> cbxColorVehi;
    private javax.swing.JComboBox<String> cbxLunaPolarizada;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JComboBox<String> cbxModelo;
    private javax.swing.JComboBox<String> cbxTipVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablitaCarros;
    private javax.swing.JTextField txtNumPlaca;
    // End of variables declaration//GEN-END:variables
}

